

service: serverless-s3


provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-south-1


functions:
  filePrint:
    handler: handler.s3file_handler
    events:
      - s3:
          bucket: incominglambda
          event: s3:ObjectCreated:*


plugins:
  - serverless-s3-remover

custom:
  remover:
    prompt: true # default value is `false`
    buckets:
      - incominglambda
      - processedlambda


resources:
  Resources:
#    IncomingBucket:
#      Type: AWS::S3::Bucket
#      DeletionPolicy: Delete
#      Properties:
#        BucketName: incominglambda

    ProcessedBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: processedlambda

    AccessLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/serverless-s3-dev
  Outputs:
     NewOutput:
       Description: "resource created"
       Value: "Resource S3 Crete"
